name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install codecov
        run: npm install -g codecov
      - name: Install Packages
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Run Unit Tests
        run: npm run test-cov && codecov -f coverage/lcov.info
